import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider.js"

const outfit=Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
      </ClerkProvider>
  );
}
